### PR TITLE
Add extra operators

### LINKED ISSUE #48: Unhandled value
From [bblfsh logs](https://github.com/bblfsh/bblfshd/issues/298) we got the following messages:

```
unhandled value: arrow ->
unhandled value: dot .
unhandled value: op_alignOf
```

<details>
<summary> Files that triggered <b> unhandled value: arrow -> </b> </summary>

```
lib/Sema/ConstraintSystem.cpp
test/SemaCXX/cxx0x-initializer-stdinitializerlist.cpp
```

</details>
<details>
<summary> Files that triggered <b> unhandled value: dot . </b> </summary>

```
lib/boost_1.60.0/boost/multi_index/mem_fun.hpp
external/bsd/llvm/dist/clang/test/CXX/dcl.decl/dcl.meaning/dcl.mptr/p3.cpp
gdb/testsuite/gdb.c++/member-ptr.cc
gdb/testsuite/gdb.c++/misc.cc
bundled/boost-1.56.0/include/boost/multi_index/detail/scope_guard.hpp
test/SemaCXX/vararg-non-pod.cpp
external/gpl3/binutils/dist/gold/testsuite/basic_test.cc
external/bsd/llvm/dist/clang/test/SemaCXX/vararg-non-pod.cpp
gnu/llvm/lib/Fuzzer/test/FuzzerUnittest.cpp
external/bsd/llvm/dist/clang/test/Analysis/member-expr.cpp
engines/titanic/messages/messages.cpp
sipXcommserverLib/src/fastdb/rtree.cpp
Framework/Kernel/src/MaterialXMLParser.cpp
Interfaces/ConsoleCommandServiceInterface.h
src/object_store.cpp
lib/boost_1.60.0/boost/msm/front/detail/row2_helper.hpp
external/bsd/llvm/dist/llvm/tools/llvm-dwp/llvm-dwp.cpp
lib/boost_1.60.0/boost/wave/util/cpp_macromap.hpp
gdb/testsuite/gdb.cp/member-ptr.cc
test/CodeGenCXX/2010-05-12-PtrToMember-Dbg.cpp
Framework/PythonInterface/mantid/api/src/CloneMatrixWorkspace.cpp
bundled/boost-1.56.0/include/boost/multi_index/member.hpp
gdb/testsuite/gdb.cp/misc.cc
Source/bmalloc/bmalloc/AsyncTask.h
ReactCommon/cxxreact/JsArgumentHelpers-inl.h
external/bsd/llvm/dist/clang/test/CodeGenCXX/2004-03-08-ReinterpretCastCopy.cpp
lib/boost_1.60.0/boost/property_tree/detail/json_parser/parser.hpp
gnu/llvm/tools/clang/lib/Lex/PreprocessingRecord.cpp
test/Analysis/pointer-to-member.cpp
Console/ConsoleCommandUtils.h
gnu/usr.bin/groff/addftinfo/addftinfo.cc
gdb/testsuite/gdb.cp/classes.cc
test/SemaCXX/incomplete-call.cpp
vital/algo/estimate_similarity_transform.cxx
external/bsd/llvm/dist/clang/test/SemaCXX/incomplete-call.cpp
gnu/llvm/include/llvm/ExecutionEngine/Orc/RPCUtils.h
libs/hwui/font/Font.cpp
lib/Parse/RAIIObjectsForParser.h
gnu/llvm/tools/llvm-dwp/llvm-dwp.cpp
lib/boost_1.60.0/boost/msm/front/state_machine_def.hpp
test/SemaCXX/unaddressable-functions.cpp
gnu/dist/toolchain/gdb/testsuite/gdb.c++/member-ptr.cc
gnu/usr.bin/binutils/gdb/testsuite/gdb.cp/misc.cc
test/CXX/dcl.decl/dcl.meaning/dcl.mptr/p3.cpp
engines/cge/vmenu.cpp
external/gpl3/gdb/dist/gdb/testsuite/gdb.cp/pr17494.cc
include/deal.II/lac/precondition.h
external/bsd/llvm/dist/clang/test/CodeGenCXX/mangle-ms-templates-memptrs.cpp
gnu/usr.bin/binutils/gdb/testsuite/gdb.cp/classes.cc
lib/boost_1.60.0/boost/python/lvalue_from_pytype.hpp
```

</details>
<details>
<summary> Files that triggered <b> unhandled value: op_alignOf -> </b> </summary>

```
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-long-1-c-int.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-short-2-c-longdouble.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-int-2-c-long.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-longdouble-2-c-short.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-float-1-c-short.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-char-2-c-longdouble.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-pointer-1-c-float.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-pointer-1-c-double.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-longdouble-1-c-pointer.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-short-1-c-pointer.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/class-short-and-virtual.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-longlong-1-c-pointer.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-int-2-c-short.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-longlong-1-c-pointer.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-char-2-c-int.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-short-2-c-longlong.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-long-1-c-pointer.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-short-1-c-longlong.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-pointer-2-c-double.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-long-2-c-short.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-longdouble-2-c-float.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-short-2-c-int.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-double-2-c-short.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-pointer-2-c-short.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-char-1-c-pointer.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-long-2-c-longdouble.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-longdouble-1-c-short.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-char-2-c-short.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-float-2-c-long.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/class-int-and-virtual.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/class-longdouble-and-virtual.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-pointer-2-c-float.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/class-double-and-virtual.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-pointer-1-c-short.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-double-1-c-longdouble.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-double-1-c-longdouble.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-char-2-c-char.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-longlong-1-c-longdouble.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-longlong-1-c-int.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-short-1-c-float.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-long-1-c-char.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-float-2-c-int.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-float-2-c-float.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-longdouble-2-c-char.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/c-longlong-2-c-short.cpp
gnu/usr.bin/gcc/gcc/testsuite/consistency.vlad/layout/class-int-and-virtual.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/class-long-and-virtual.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-int-1-c-longdouble.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-longdouble-2-c-short.cpp
gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-char-2-c-short.cpp
```

### PR DESCRIPTION
**Pull request by kuba--**
Signed-off-by: kuba-- <kuba@sourced.tech>

Add extra operators ("dot .", "arrow ->", "op_alignOf")
Closes: https://github.com/bblfsh/cpp-driver/issues/48

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/56)

### CODE REVIEW

**Review by creachadair — COMMENTED** [review]
This mostly looks fine, but I'm confused as to why there are different names for the same operators. Is that something we did, or did we fall into that from CDT?

> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/56#-:-LliHo3d8GtX_30YrQTQ:b-4u8exl)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @bzz, @creachadair, @dennwc, @kuba--, and @ncordon)

___
*[driver/normalizer/annotation.go, line 106 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/56#-LliH_D77xwiA7GqoUuy:-LliH_D77xwiA7GqoUuz:bgukpcd) ([raw file](https://github.com/bblfsh/cpp-driver/blob/b01af44b5c7be7d5ce84dd4e420556149cd6ee20/driver/normalizer/annotation.go#L106)):*
> ```Go
> 	unaryExprRoles = StringToRolesMap(map[string][]role.Role{
> 		"op_alignof":             {role.Unary, role.Incomplete},
> 		"op_alignOf":             {role.Unary, role.Incomplete},
> ```

Are these names from CDT? And did they really define this with two variants that differ only by capitalization?
___
*[fixtures/c-long-1-c-pointer.cpp, line 17 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/56#-LliHB_t-fYuUHa67tHu:-LliHB_u8BfG0JRXDReL:b-wmx1ca) ([raw file](https://github.com/bblfsh/cpp-driver/blob/b01af44b5c7be7d5ce84dd4e420556149cd6ee20/fixtures/c-long-1-c-pointer.cpp#L17)):*
> ```cpp
> 
> int main (void) {
>   printf ("++Class with pointer inhereting class with long:\n");
> ```

typo: inheriting

**Review by kuba-- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/56)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @bzz, @creachadair, @dennwc, and @ncordon)

___
*[driver/normalizer/annotation.go, line 106 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/56#-LliH_D77xwiA7GqoUuy:-Llkzy4_6JuWu__Syug_:brq22kh) ([raw file](https://github.com/bblfsh/cpp-driver/blob/b01af44b5c7be7d5ce84dd4e420556149cd6ee20/driver/normalizer/annotation.go#L106)):*
<details><summary><i>Previously, creachadair (M. J. Fromberger) wrote…</i></summary><blockquote>

Are these names from CDT? And did they really define this with two variants that differ only by capitalization?
</blockquote></details>

Yep, this looks a little bit confusing for me, as well. But in CDT serializer distinguishes _unary expressions_ (https://github.com/bblfsh/cpp-driver/blob/master/native/src/main/java/tech/sourced/babelfish/JsonASTVisitor.java#L344) 
from _typeid expressions_ (https://github.com/bblfsh/cpp-driver/blob/master/native/src/main/java/tech/sourced/babelfish/JsonASTVisitor.java#L410),

I suppose it's CDT convention (I don't believe anyone from our team changed it in the past), so I didn't want to change it (the safe approach in this PR, just to fix the bug).
Similarly with two other roles: `dot .` and `arrow ->` - they are not super informative, but I decided not to change it so far (we can discuss it later, if needed)

**Review by dennwc — APPROVED** [review]
> Reviewed 11 of 11 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/56)* status: all files reviewed, 1 unresolved discussion (waiting on @bzz, @creachadair, and @ncordon)

**Comment by ncordon** [comment]
IMHO it's really difficult to read the test files (the `.cpp` ones). Is there a way to simplify those for ease of maintenance? Or are we testing complex syntax for some specific purpose?

**Review by ncordon — APPROVED** [review]
> Reviewed 7 of 11 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/56)* status: all files reviewed, 1 unresolved discussion (waiting on @bzz and @creachadair)

**Review by kuba-- — COMMENTED** [review]
Test fixtures are not written by me. These are just snippets from projects like gcc, netbsd, or boost.
I've just tailored them (left only parts which needs to be tested, like operators `.*`, `__align__`, etc.).
I don't expect anybody will modify them.

If you go to the issue description, you'll notice that _buggy_ files are:
`lib/boost_1.60.0/boost/multi_index/mem_fun.hpp`
or `gnu/dist/gcc/gcc/testsuite/consistency.vlad/layout/c-long-1-c-int.cpp`
I just copied and tested cpp-dirver against them.

> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/56#-:-LllYFtv3O1I3NmI2-_F:b-6oj057)* status: all files reviewed, 1 unresolved discussion (waiting on @bzz and @creachadair)

**Review by creachadair — APPROVED** [review]
Makes sense to me.

> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/56#-:-Lllfzly1iJvpqrlzPxW:b-a7ljwd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bzz)

___
*[driver/normalizer/annotation.go, line 106 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/56#-LliH_D77xwiA7GqoUuy:-LllfM7JEi2k_aPBfeZo:b-m9ap6y) ([raw file](https://github.com/bblfsh/cpp-driver/blob/b01af44b5c7be7d5ce84dd4e420556149cd6ee20/driver/normalizer/annotation.go#L106)):*
<details><summary><i>Previously, kuba-- (Kuba Podgórski) wrote…</i></summary><blockquote>

Yep, this looks a little bit confusing for me, as well. But in CDT serializer distinguishes _unary expressions_ (https://github.com/bblfsh/cpp-driver/blob/master/native/src/main/java/tech/sourced/babelfish/JsonASTVisitor.java#L344) 
from _typeid expressions_ (https://github.com/bblfsh/cpp-driver/blob/master/native/src/main/java/tech/sourced/babelfish/JsonASTVisitor.java#L410),

I suppose it's CDT convention (I don't believe anyone from our team changed it in the past), so I didn't want to change it (the safe approach in this PR, just to fix the bug).
Similarly with two other roles: `dot .` and `arrow ->` - they are not super informative, but I decided not to change it so far (we can discuss it later, if needed)
</blockquote></details>

If this is just a lookup table to map CDT strings into roles, that's fine. If that's the case, though, could you add a brief comment somewhere nearby (maybe at the top of the `var` block) to that effect?

**Review by dennwc — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/56)* status: all files reviewed, 1 unresolved discussion (waiting on @bzz and @kuba--)

**Comment by ncordon** [comment]
Thanks for the clarification :) :lgtm:

**Review by bzz — APPROVED** [review]
> These are just snippets from projects like gcc, netbsd, or boost. 

as drivers are distributed under the GPLv3, and even although we do not have source-based release artifacts, it may be wise to exercise cautions when copy code from other project, distributed under a different license.

Having simple synthetic examples might help avoid having that discussion altogether.

> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/56#-:-LlmN0SS0uAVRSbDjNcH:bblpv8p)* status: all files reviewed, 1 unresolved discussion (waiting on @kuba--)

**Review by kuba-- — COMMENTED** [review]
these are just fixtures, and as i mentioned tailored snippets.

> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/56#-:-Llm_vWP3RnSoBcgqM4I:b4v120p)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dennwc — APPROVED** [review]
@bzz I agree this is an important issue, but we'll need to check _all_ the fixtures in this case. I have no idea what is the source for most of them. So let's discuss it separately. Can you please open an issue in SDK or bblfshd?

> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/56#-:-LlmzAEIBUw7h-oPl-mY:b8kbxyr)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
