### PR TITLE
Add program to fixtures for performance measure

### PR DESCRIPTION
**Pull request by tsolakoua**
Added the [Ethiopian Multiplication](https://www.rosettacode.org/wiki/Ethiopian_multiplication) C++ solution. 
Related to https://github.com/bblfsh/bblfshd/issues/220

### CODE REVIEW

**Review by juanjux — APPROVED** [review]
Thanks for the PR @tsolakoua!

**Comment by tsolakoua** [comment]
@juanjux I think I also need to add the tests, right? This is the feedback I had from the [Go version](https://github.com/bblfsh/go-driver/pull/33) so I suppose I should do the same here as well.

**Comment by juanjux** [comment]
Don't worry I'll regenerate them from the source file since I'm working on this driver right now.

**Comment by tsolakoua** [comment]
thanks @juanjux ! There are 14 more cpp files that I need to upload, I suppose 1 PR with all of them would be ok.

**Comment by juanjux** [comment]
Yes, perfectly fine.

**Pull request merged**
