### PR TITLE
Fix Unicode positions

### PR DESCRIPTION
**Pull request by dennwc**
Fix Unicode positions. Ideally this PR should also enable enable the token verifier, but it's not possible right now due to the way AST is structured. Some work in SDK is required to make it work.

Signed-off-by: Denys Smirnov <denys@sourced.tech>

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/40)

### CODE REVIEW

**Review by bzz — APPROVED** [review]

**Review by creachadair — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/40)* status: all files reviewed, 1 unresolved discussion (waiting on @dennwc)

___
*[driver/fixtures/fixtures_test.go, line 37 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/40#-Lg8GKip1r3axglR02ft:-Lg8GKip1r3axglR02fu:bt8w6nw) ([raw file](https://github.com/bblfsh/cpp-driver/blob/6be467b755a3112ce87931737d08b09344c24d31/driver/fixtures/fixtures_test.go#L37)):*
> ```Go
> 		},
> 	},
> 	// TODO: This won't really work because of the C++ macros expansion.
> ```

I don't quite follow: Of course macro expansions affect position, but if the AST we generate doesn't expand the macro anyway aren't the locations correct?

**Review by dennwc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/40)* status: all files reviewed, 1 unresolved discussion (waiting on @creachadair)

___
*[driver/fixtures/fixtures_test.go, line 37 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/40#-Lg8GKip1r3axglR02ft:-Lg8QHJi7GUG9tjwBfW3:bdh73h9) ([raw file](https://github.com/bblfsh/cpp-driver/blob/6be467b755a3112ce87931737d08b09344c24d31/driver/fixtures/fixtures_test.go#L37)):*
<details><summary><i>Previously, creachadair (M. J. Fromberger) wrote…</i></summary><blockquote>

I don't quite follow: Of course macro expansions affect position, but if the AST we generate doesn't expand the macro anyway aren't the locations correct?
</blockquote></details>

Turned out it _does_ expand macros that are in the same file. It sill preserves the AST structure for it but breaks the positional info that we use.

To give an example, there was a macro that joins two values, so the source line is `JOIN(3, 4)`. But the preprocessor actually replaces it with a string `34`, so the token verification gets confused and can't verify it based on the source file.

So maybe other positional info is also incorrect for files that use macros.

**Review by creachadair — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/40)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[driver/fixtures/fixtures_test.go, line 37 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/40#-Lg8GKip1r3axglR02ft:-Lg8WZlXDVpLVZ0qqqiR:b4e6uk5) ([raw file](https://github.com/bblfsh/cpp-driver/blob/6be467b755a3112ce87931737d08b09344c24d31/driver/fixtures/fixtures_test.go#L37)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Turned out it _does_ expand macros that are in the same file. It sill preserves the AST structure for it but breaks the positional info that we use.

To give an example, there was a macro that joins two values, so the source line is `JOIN(3, 4)`. But the preprocessor actually replaces it with a string `34`, so the token verification gets confused and can't verify it based on the source file.

So maybe other positional info is also incorrect for files that use macros.
</blockquote></details>

Urk, that's a little scary. I wonder if we can disable macro expansion entirely rather than have it depend on where the definition resides. Not a topic for this PR, though.

**Review by dennwc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/40)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[driver/fixtures/fixtures_test.go, line 37 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/40#-Lg8GKip1r3axglR02ft:-Lg8aCK1C3R4PGfSk18o:bjf48ez) ([raw file](https://github.com/bblfsh/cpp-driver/blob/6be467b755a3112ce87931737d08b09344c24d31/driver/fixtures/fixtures_test.go#L37)):*
<details><summary><i>Previously, creachadair (M. J. Fromberger) wrote…</i></summary><blockquote>

Urk, that's a little scary. I wonder if we can disable macro expansion entirely rather than have it depend on where the definition resides. Not a topic for this PR, though.
</blockquote></details>

Opened an issue for it: https://github.com/bblfsh/cpp-driver/issues/41

**Pull request merged**
