### PR TITLE
catch cdt casting exceptions

### LINKED ISSUE #54: Native driver crashed
From [bblfsh logs](https://github.com/bblfsh/bblfshd/issues/298) we got the error `native driver crashed`

<details>
<summary> Files that produced the error </summary>

```
udoc/headerfile.h
InputModuleOIS/Exports.cpp
release/src-rt/linux/linux-2.6/scripts/squashfs/lzma/C/7zip/Compress/Branch/x86.h
LibraryModule/StableHeaders.cpp
src/others/squashfs-4.0-realtek/lzma/CPP/7zip/Bundles/Alone7z/StdAfx.cpp
core/md5.h
ProtocolUtilities/LoginCredentials.h
PhysicsModule/CollisionShapeUtils.h
Foundation/ComponentManager.cpp
rosapps/applications/sysutils/utils/sdkparse/skip_ws.cpp
Engine/Source/Runtime/Android/AndroidRuntimeSettings/Private/AndroidRuntimeSettingsModule.cpp
gnu/dist/binutils/ld/testsuite/ld-cdtest/cdtest-bar.cc
encodings/gbk.h
TestModule/TestService.cpp
Templates/TP_Vehicle/Source/TP_Vehicle/TP_Vehicle.cpp
PythonScriptModule/TransformDecorator.h
SceneManager/StableHeaders.cpp
TelepathyIMModule/CommunicationUI/ConfigHelper.cpp
UiModule/Inworld/Notifications/NotificationLogWidget.h
ld/testsuite/ld-cdtest/cdtest-bar.cc
src/Core/TundraProtocolModule/StableHeaders.cpp
TelepathyIMModule/CommunicationUI/FriendListItem.cpp
sketches/Trident/CModule.cpp
smtp/smtpauth.h
Foundation/QtInputMouseEvent.cpp
encodings/cp.h
UiModule/Common/UiVisibilityAction.cpp
PythonScriptModule/TransformDecorator.cpp
EnvironmentModule/StableHeaders.cpp
smtp/smtpparser.h
Engine/Source/Runtime/Core/Private/HAL/IPlatformFileLogWrapper.cpp
src/EntityComponents/EC_Ruler/StableHeaders.cpp
RexLogicModule/NotificationWidget.h
WorldBuildingModule/StableHeaders.cpp
db/pgmessage.h
Core/CoreStableHeaders.cpp
CAVEStereoModule/CAVEManager.cpp
Tests/Tutorial/Step3/tutorial.cxx
test/SemaCXX/warn-sysheader-macro.cpp
UiModule/Inworld/ControlPanel/BackdropWidget.h
src/Core/ECEditorModule/LineEditPropertyFactory.cpp
PythonScriptModule/QEC_Prim.cpp
imap/handlers/rename.h
Engine/Source/Developer/AITestSuite/Private/TestLogger.cpp
RexLogicModule/EventHandlers/SceneEventHandler.h
Engine/Source/Runtime/InputCore/Private/InputCoreModule.cpp
ReXLogic/EC_OpenSimAvatar.cpp
Engine/Source/Runtime/Sockets/Private/MultichannelTCP.cpp
CommunicationModule/CommunicationUI/FriendListItem.cpp
kpresenter/rotationdialogimpl.cc
```

</details>

### PR DESCRIPTION
**Pull request by kuba--**
Signed-off-by: kuba-- <kuba@sourced.tech>
Closes https://github.com/bblfsh/cpp-driver/issues/54

We don't have any test cases to verify errors/failures.
We need to add `testErrors` to sdk, then we can add more test cases to drivers.
So far this PR tries to catch CDT internal casting exceptions and set status to `error` (instead of default `fatal`).

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)

### CODE REVIEW

**Review by dennwc — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bzz, @creachadair, and @ncordon)

**Review by creachadair — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bzz, @creachadair, and @ncordon)

**Comment by ncordon** [comment]
___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 12 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LmuCVxtEJYjuKeMoIUh:-LmuCVxtEJYjuKeMoIUi:b-usui28) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L12)):*
> ```Java
>     static class ResponseSendException extends IOException {
>         private final static String cdtPackage = "org.eclipse.cdt";
>         private final static int maxDepth = 3;
> ```

Why does this only inspect 3 levels of exceptions at max? I mean, could the `CastException` be deeper but we are not reaching it?

**Review by ncordon — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)* status: all files reviewed, 1 unresolved discussion (waiting on @bzz and @kuba--)

**Review by kuba-- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)* status: all files reviewed, 1 unresolved discussion (waiting on @bzz and @ncordon)

___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 12 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LmuCVxtEJYjuKeMoIUh:-Lmv6CmRB3ZiAGbmsfH4:bi55igw) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L12)):*
<details><summary><i>Previously, ncordon (Nacho Cordón) wrote…</i></summary><blockquote>

Why does this only inspect 3 levels of exceptions at max? I mean, could the `CastException` be deeper but we are not reaching it?
</blockquote></details>

First of all i had to pick some number (i didn't want to pick to high, but frankly started from 10). 
For this particular case we get the cast exception in the first iteration (after unwrapping the JacksonMap exception). So hypothetically, for any number we can miss it

**Review by bzz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)* status: all files reviewed, 4 unresolved discussions (waiting on @kuba-- and @ncordon)

___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 12 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LnHfAXD2zITbh3xs7G7:-LnHfAXD2zITbh3xs7G8:bhwis9g) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L12)):*
> ```Java
>     static class ResponseSendException extends IOException {
>         private final static String cdtPackage = "org.eclipse.cdt";
>         private final static int maxDepth = 3;
> ```

:pray: let's also make sure we follow naming conventions of the language: e.g for [constants](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names)
___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 15 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LnHex9A28K3pfhMyb4C:-LnHex9A28K3pfhMyb4D:b-75a9l5) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L15)):*
> ```Java
>         private final Throwable e;
> 
>         ResponseSendException(final Throwable e) { super(e); this.e = e; }
> ```

As this is not C++, there is no need for adding `final` here.

And in case of multiple expressions, it's [preferred to use multiple lines](https://google.github.io/styleguide/javaguide.html#s4.3-one-statement-per-line) :wink: 
___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 16 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LnHhkrl5DGKG8xTPtMD:-LnHhkrl5DGKG8xTPtME:b7p9z1j) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L16)):*
> ```Java
> 
>         ResponseSendException(final Throwable e) { super(e); this.e = e; }
>         boolean isCDTCastException() {
> ```

Method names in Java follow [camelCase](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case) even for acronyms.

I would also suggest adding a JavaDoc, mentioning that the current implementation uses a heuristics to answer this question - that may also help to address the the @ncordon concern with the magic number above
___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 38 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LnHiRhP3m6UA6p4_4eE:-LnHiRhQADsaMP69RgkT:b56k1l4) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L38)):*
> ```Java
>         ok {
>             @Override
>             public String toString() {
> ```

Very much a nit-pick, but putting an `@Override` on the same line as method declaration is a [customary way](https://google.github.io/styleguide/javaguide.html#s4.8.1-enum-classes) of saving some vertical space.

**Review by bzz — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)* status: all files reviewed, 4 unresolved discussions (waiting on @kuba-- and @ncordon)

**Review by kuba-- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)* status: all files reviewed, 4 unresolved discussions (waiting on @bzz, @kuba--, and @ncordon)

___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 12 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LnHfAXD2zITbh3xs7G7:-LnJYLZoD2sF4ixdCAnR:bvbdl5) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L12)):*
<details><summary><i>Previously, bzz (Alexander) wrote…</i></summary><blockquote>

:pray: let's also make sure we follow naming conventions of the language: e.g for [constants](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names)
</blockquote></details>

OK, I didn't know we follow any convention. So, working with 3rd party CDT I tried to adopt what have in CDT (because it's the biggest part of cpp-driver). If you take a look into CDT it doesn't follow any Google's rules, e.g.:
```java
public interface IASTNameOwner {
	/**
	 * Role of name in this context is a declaration.
	 */
	public static final int r_declaration = 0;
	/**
	 * Role of name in this construct is a reference.
	 */
	public static final int r_reference = 1;
```

**Review by kuba-- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)* status: all files reviewed, 4 unresolved discussions (waiting on @bzz and @ncordon)

___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 12 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LnHfAXD2zITbh3xs7G7:-LnJYtfh6WYRRFtpPXiO:b-vuuwch) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L12)):*
> what
___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 15 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LnHex9A28K3pfhMyb4C:-LnJZcVi7MZ4CIGGjha4:bao4o1w) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L15)):*
<details><summary><i>Previously, bzz (Alexander) wrote…</i></summary><blockquote>

As this is not C++, there is no need for adding `final` here.

And in case of multiple expressions, it's [preferred to use multiple lines](https://google.github.io/styleguide/javaguide.html#s4.3-one-statement-per-line) :wink: 
</blockquote></details>

...just to emphasize it won't be reassigned and to allow reuse it (potentially) in local subclasses.
___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 16 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LnHhkrl5DGKG8xTPtMD:-LnJZElk9LccneOrnhQt:b-kyasm4) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L16)):*
<details><summary><i>Previously, bzz (Alexander) wrote…</i></summary><blockquote>

Method names in Java follow [camelCase](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case) even for acronyms.

I would also suggest adding a JavaDoc, mentioning that the current implementation uses a heuristics to answer this question - that may also help to address the the @ncordon concern with the magic number above
</blockquote></details>

Look at the comment above - That's why I capitalized `CDT` and and didn't uppercase `final statics`.
Anyway, I'll apply if it's our style guide choice.

**Review by kuba-- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @bzz, @dennwc, and @ncordon)

___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 12 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LmuCVxtEJYjuKeMoIUh:-LnP-vkL0bkNB6t62j5U:b-896fix) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L12)):*
<details><summary><i>Previously, kuba-- (Kuba Podgórski) wrote…</i></summary><blockquote>

First of all i had to pick some number (i didn't want to pick to high, but frankly started from 10). 
For this particular case we get the cast exception in the first iteration (after unwrapping the JacksonMap exception). So hypothetically, for any number we can miss it
</blockquote></details>

Done.
___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 15 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LnHex9A28K3pfhMyb4C:-LnP-tZ7AyIjmFQ5Qd62:b-896fix) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L15)):*
<details><summary><i>Previously, kuba-- (Kuba Podgórski) wrote…</i></summary><blockquote>

...just to emphasize it won't be reassigned and to allow reuse it (potentially) in local subclasses.
</blockquote></details>

Done.
___
*[native/src/main/java/tech/sourced/babelfish/DriverResponse.java, line 16 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/61#-LnHhkrl5DGKG8xTPtMD:-LnP-ttBBPZStALyiqxO:b-896fix) ([raw file](https://github.com/bblfsh/cpp-driver/blob/db00519727eaa198fca2ffee7ffd0f5481224439/native/src/main/java/tech/sourced/babelfish/DriverResponse.java#L16)):*
<details><summary><i>Previously, kuba-- (Kuba Podgórski) wrote…</i></summary><blockquote>

Look at the comment above - That's why I capitalized `CDT` and and didn't uppercase `final statics`.
Anyway, I'll apply if it's our style guide choice.
</blockquote></details>

Done.

**Review by ncordon — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)* status: all files reviewed, 4 unresolved discussions (waiting on @bzz and @ncordon)

**Review by dennwc — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)* status: all files reviewed, 4 unresolved discussions (waiting on @bzz and @ncordon)

**Comment by kuba--** [comment]
I've solved all issues mentioned by @bzz - can we merge it?

**Review by dennwc — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/61)* status: all files reviewed, 4 unresolved discussions (waiting on @bzz and @ncordon)

**Pull request merged**
