### PR TITLE
Missing Operator role

### PR DESCRIPTION
**Pull request by BFergerson**
I think this is correct. Nothing in the CPP AST plays the **Operator** role.

Edit: Or maybe **Operator** has to be added to each operator in `binaryExprRoles`?

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/59)

### CODE REVIEW

**Review by kuba-- — APPROVED** [review]

**Review by kuba-- — CHANGES_REQUESTED** [review]
LGTM, but the CI is failing, so please fix tests

**Review by dennwc — APPROVED** [review]

**Comment by dennwc** [comment]
@BFergerson The tests needs to be re-run and modified fixtures to be committed. Can you please run `go run ./test.go` locally so it regenerates the fixtures? You will also need to rename `fixtures/*_got` to `fixtures/*` to "accept" changes in those files.

**Comment by BFergerson** [comment]
@dennwc, do you know how to solve this issue:
```
brandon@jimmy:~/IdeaProjects/cpp-driver$ go run ./test.go
test.go:8:2: cannot find package "github.com/bblfsh/sdk/v3/build" in any of:
        /usr/lib/go-1.10/src/github.com/bblfsh/sdk/v3/build (from $GOROOT)
        /home/brandon/go/src/github.com/bblfsh/sdk/v3/build (from $GOPATH)
```

I also tried `go test ./driver` and that shows:
```
brandon@jimmy:~/IdeaProjects/cpp-driver$ go test ./driver
driver/main.go:4:2: cannot find package "github.com/bblfsh/cpp-driver/driver/impl" in any of:
        /usr/lib/go-1.10/src/github.com/bblfsh/cpp-driver/driver/impl (from $GOROOT)
        /home/brandon/go/src/github.com/bblfsh/cpp-driver/driver/impl (from $GOPATH)
driver/main.go:5:2: cannot find package "github.com/bblfsh/cpp-driver/driver/normalizer" in any of:
        /usr/lib/go-1.10/src/github.com/bblfsh/cpp-driver/driver/normalizer (from $GOROOT)
        /home/brandon/go/src/github.com/bblfsh/cpp-driver/driver/normalizer (from $GOPATH)
driver/main.go:7:2: cannot find package "github.com/bblfsh/sdk/v3/driver/server" in any of:
        /usr/lib/go-1.10/src/github.com/bblfsh/sdk/v3/driver/server (from $GOROOT)
        /home/brandon/go/src/github.com/bblfsh/sdk/v3/driver/server (from $GOPATH)
```

I've run `export GO111MODULE=on` before both of these commands.

**Comment by kuba--** [comment]
@BFergerson - try `GO111MODULE=on go mod vendor` and then `go run ...`

**Comment by BFergerson** [comment]
@kuba--, no go:
```
brandon@jimmy:~/IdeaProjects/cpp-driver$ export GO111MODULE=on go mod vendor
brandon@jimmy:~/IdeaProjects/cpp-driver$ go run ./test.go
test.go:8:2: cannot find package "github.com/bblfsh/sdk/v3/build" in any of:
        /usr/lib/go-1.10/src/github.com/bblfsh/sdk/v3/build (from $GOROOT)
        /home/brandon/go/src/github.com/bblfsh/sdk/v3/build (from $GOPATH)
brandon@jimmy:~/IdeaProjects/cpp-driver$ go test ./driver
driver/main.go:4:2: cannot find package "github.com/bblfsh/cpp-driver/driver/impl" in any of:
        /usr/lib/go-1.10/src/github.com/bblfsh/cpp-driver/driver/impl (from $GOROOT)
        /home/brandon/go/src/github.com/bblfsh/cpp-driver/driver/impl (from $GOPATH)
driver/main.go:5:2: cannot find package "github.com/bblfsh/cpp-driver/driver/normalizer" in any of:
        /usr/lib/go-1.10/src/github.com/bblfsh/cpp-driver/driver/normalizer (from $GOROOT)
        /home/brandon/go/src/github.com/bblfsh/cpp-driver/driver/normalizer (from $GOPATH)
driver/main.go:7:2: cannot find package "github.com/bblfsh/sdk/v3/driver/server" in any of:
        /usr/lib/go-1.10/src/github.com/bblfsh/sdk/v3/driver/server (from $GOROOT)
        /home/brandon/go/src/github.com/bblfsh/sdk/v3/driver/server (from $GOPATH)
```

**Comment by kuba--** [comment]
ohh, I see you use go-1.10. You have to upgrade go version which supports modules.
At least 1.11, but ideally 1.12+

**Comment by BFergerson** [comment]
@kuba--, thanks that seems to be working. Right now all its output is:
```
brandon@jimmy:~/IdeaProjects/cpp-driver$ GO111MODULE=on go mod vendor
go: finding github.com/uber/jaeger-client-go v2.16.0+incompatible
... (ommitted for brevity) ...

brandon@jimmy:~/IdeaProjects/cpp-driver$ go run ./test.go
+ docker build -q .
```
but I assume that's normal?

@kuba--, my next question is whether or not it's even correct to add the **Operator** role where I added it. Wouldn't that make everything in `binaryExprRoles` an **Operator** (like max and min)?

**Comment by dennwc** [comment]
@BFergerson yes, an `Operator` must be attached to any node that has a `@token` with an operator. In case of C++ there is no dedicated node for an operator, so the role will be on the `BinaryExpression` node.

**Comment by BFergerson** [comment]
@kuba--, would you mind helping me finish this? I've tried to fix the DCO several times and I'm not sure what the CI issue is alluding to.

**Comment by kuba--** [comment]
Regarding DCO - you have to sign your commit, usually I `git commit -s -a .`
what appends to the comment a signature like:
`Signed-off-by: name email@address`
it should satisfy DCO (You can also assign GPG if you want).

Regarding `_integration`, I have just silly question - did you modify `.uast`, `.sem` files manually or you removed and regenerated ?
CI error is not informative, and I cannot reproduce it locally. I'll take a look closer

**Comment by ncordon** [comment]
Hi @BFergerson ! There are commits which are not signed-off. In order for the DCO check to pass, you have to sign-off all the commits in the PR. Problem now is that the history stack has a lot of deep commits not signed-off and it is harder to modify the messages for those commits, but it is fixable. First of all I would recommend you make a copy of the folder holding the repo in case anything goes wrong. The way I would do that (be extra careful because it involves a `push --force` which is always risky):

```
git rebase -i 7654fbfb8
```

A text editor should appear. You should modify the `fix tests` line with an `edit`, as it is shown in the image and close the buffer:
rebase

Then you can edit the commit without DCO. It would say there is a fusion conflict, fix it and commit the files with:

```
git add . && git commit -s -a && git rebase --continue
```

until you unwind the whole stack of commits you need to modify. The last step of the rebase you should only do a `git rebase --continue` to finish the rebase. Note this procedure would also clean the history of merges. Finally when you have a clean and signed-off history, `git push --force` to update your branch.

**Pull request closed without merging**
