### PR TITLE
benchmark: add large file

### PR DESCRIPTION
**Pull request by tsolakoua**
@juanjux It fails while generating tests. Part of the results: 

```
--- FAIL: TestCppDriver (13.34s)
    --- FAIL: TestCppDriver/native (5.12s)
        --- FAIL: TestCppDriver/native/_integration (2.01s)
        	require.go:794: 
        			Error Trace:	fixtures.go:168
        			Error:      	Received unexpected error:
        			            	driver failure: read |0: i/o timeout
        			            	
        			            	github.com/bblfsh/cpp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/native.(*Driver).Parse
        			            		/go/src/github.com/bblfsh/cpp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/native/native.go:192
        			            	github.com/bblfsh/cpp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/fixtures.(*Suite).testFixturesNative.func1
        			            		/go/src/github.com/bblfsh/cpp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/fixtures/fixtures.go:159
        			            	testing.tRunner
        			            		/usr/local/go/src/testing/testing.go:777
        			            	runtime.goexit
        			            		/usr/local/go/src/runtime/asm_amd64.s:2361
        			Test:       	TestCppDriver/native/_integration
        --- FAIL: TestCppDriver/native/anonymous_class_declaration (0.29s)
        	require.go:301: 
        			Error Trace:	fixtures.go:186
        			Error:      	unexpected AST returned by the driver
        			Test:       	TestCppDriver/native/anonymous_class_declaration
        			Messages:   	run diff command to debug:
        			            	diff -d ./fixtures/anonymous_class_declaration.cpp.native_got ./fixtures/anonymous_class_declaration.cpp.native
```

### CODE REVIEW

**Comment by juanjux** [comment]
Yeah, it's a timeout, this driver is slow-ish on parsing so big files produce them. We have planned to make how the timeouts work so we can increase them.

**Review by juanjux — APPROVED** [review]

**Comment by bzz** [comment]
Would it be ok to merge this guy as is? 

Or do we want to keep it open until generation passes e.g with increased timeouts?

**Comment by juanjux** [comment]
Second option, waiting until we've custom timeouts. Merging would break the build which would make difficult to detect other problems.

**Comment by juanjux** [comment]
Looks like changes in the new version made it a little faster and now travis doesn't timeout with this file, so I'm merging - thanks @tsolakoua!

**Pull request merged**
