### PR TITLE
Serialize comments for preproc (drop include comments for semantic).

### LINKED ISSUE #60: Comments disappearing in beginning of file
Hey ! While working on `uast2clickhouse` I noticed that, if you take a file with this structure:

```
// comment 1
#pragma once
// comment 2
#include <unordered_map>
// comment 3
#include <SFML/Graphics.hpp>
// comment 4
namespace gui
// comment 5
{
class sfml2_font : public font_i
{
public:
    sfml2_font(const sf::Font& font);
};
}
```

Then the comments 1 through 4 do not appear in the UAST. For example, for [this file](https://github.com/Nocte-/hexahedra/blob/master/hexa/client/gui/sfml2.hpp) from which I based my example, the licensing block at the beginning completely disappears. Was wondering if this was expected behavior, or indeed a bug?

### PR DESCRIPTION
**Pull request by kuba--**
Signed-off-by: kuba-- <kuba@sourced.tech>
This PR is a partly work to fix: https://github.com/bblfsh/cpp-driver/issues/60

Generally we loose _pre processor_ and _namespace_ comments in native AST.
This PR adds _pre processor_ comments (_namespaces_ are pretty tricky and can be done in next PR).
So far, we have to drop _leading comments_ for _includes_, based on discussion with @dennwc:
> And since C++ driver doesn't yet have machinery to move comments around, we should drop the field for now, as done for other node types in this driver. Later we can come back and fix it properly.

---
Note:
`native/src/test/resources/parserequest.go` is a small tool which serializes source code to json, so you can test it out directly with native _CDT_ parser.

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)

### CODE REVIEW

**Review by dennwc — CHANGES_REQUESTED** [review]
> Reviewed 7 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: 7 of 19 files reviewed, 6 unresolved discussions (waiting on @bzz, @creachadair, @dennwc, @kuba--, and @ncordon)

___
*[driver/normalizer/normalizer.go, line 136 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXf0HtB85-oxpoB5ig:-LnXf0HtB85-oxpoB5ih:b-zbda0o) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/driver/normalizer/normalizer.go#L136)):*
> ```Go
> 	// Following two cases (MapSemantic("ASTInclusionStatement") are replacement
> 	// for the previous case object:
> 	// CasesObj("isSystemCase", Obj{},
> ```

This snippet may change, so maybe we can just refer to existing code? E.g. "see `CasesObj("isSystemCase", ...)`"
___
*[driver/normalizer/normalizer.go, line 140 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXgSv09pVEGIEfV8pM:-LnXgSv09pVEGIEfV8pN:b-653mvo) ([raw file](https://github.com/bblfsh/cpp-driver/blob/deaaca6dd82c7bf7c39d08899048417b0eeab31f/driver/normalizer/normalizer.go#L140)):*
> ```Go
> 					"Name":     Var("path"),
> 					"IsSystem": Bool(true),
> 					// Always empty on current tests, this should detect other cases
> ```

Can you please preserve those comments?

Also, adding a `FIXME` for dropped comments may be a good idea.
___
*[driver/normalizer/normalizer.go, line 158 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXkNTx1akVFD2ngo8q:-LnXkNTx1akVFD2ngo8r:b-b6ndme) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/driver/normalizer/normalizer.go#L158)):*
> ```Go
> 	// we must drop them in the semantic representation.
> 	//
> 	// FIXME(kuba--): I don't know how to drop "LeadingComments" in CasesObj,
> ```

You could also try `Map(Cases(...))` instead of `MapObj(CasesObj(...))`.
___
*[fixtures/preproc_comments.cpp, line 7 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXiYOCCDDmBqQxLh-D:-LnXiYOCCDDmBqQxLh-E:bp31lv8) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/fixtures/preproc_comments.cpp#L7)):*
> ```cpp
> // comment 3
> #include <SFML/Graphics.hpp>
> // comment 4
> ```

It looks like there is no `comment 4` in the AST.

I heard that in Japanese number "4" pronounced the same way as "death", so they try to avoid it. Is it the case for this PR? :trollface: 

Anyway, I assume you plan to add comments for namespaces in the next one, correct?
___
*[fixtures/preproc_comments.cpp, line 17 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXgy8W0m6ixJ-Hj-zs:-LnXgy8W0m6ixJ-Hj-zt:b-e5fjza) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/fixtures/preproc_comments.cpp#L17)):*
> ```cpp
> };
> }
> ```

We can also tests trailing comments:

```
#line xxx
// trailing comment
(EOF)
```
___
*[native/src/test/resources/parserequest.go, line 1 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXefRSETrLM04b_IeZ:-LnXefRSETrLM04b_Ie_:bbuup6z) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/native/src/test/resources/parserequest.go#L1)):*
> ```Go
> package main
> ```

Hehe, nice :) Should be a part of `bblfsh-sdk` tool really ;)

**Review by kuba-- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: 6 of 23 files reviewed, 6 unresolved discussions (waiting on @bzz, @creachadair, @dennwc, and @ncordon)

___
*[driver/normalizer/normalizer.go, line 136 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXf0HtB85-oxpoB5ig:-LnlNGL44_v2KLjr4AZ3:b-896fix) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/driver/normalizer/normalizer.go#L136)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

This snippet may change, so maybe we can just refer to existing code? E.g. "see `CasesObj("isSystemCase", ...)`"
</blockquote></details>

Done.
___
*[driver/normalizer/normalizer.go, line 140 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXgSv09pVEGIEfV8pM:-LnlNaSv6qi8PFPMHy-5:b-896fix) ([raw file](https://github.com/bblfsh/cpp-driver/blob/deaaca6dd82c7bf7c39d08899048417b0eeab31f/driver/normalizer/normalizer.go#L140)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Can you please preserve those comments?

Also, adding a `FIXME` for dropped comments may be a good idea.
</blockquote></details>

Done.
___
*[driver/normalizer/normalizer.go, line 158 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXkNTx1akVFD2ngo8q:-LnlNLN72RFGbwMmAu8j:byleipi) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/driver/normalizer/normalizer.go#L158)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

You could also try `Map(Cases(...))` instead of `MapObj(CasesObj(...))`.
</blockquote></details>

How can I use Map(Cases) in this case (where you need to drop _LeadingComments_)?
___
*[fixtures/preproc_comments.cpp, line 7 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXiYOCCDDmBqQxLh-D:-LnlNcnWAk0hC-kqkKEj:b-ywwaqi) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/fixtures/preproc_comments.cpp#L7)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

It looks like there is no `comment 4` in the AST.

I heard that in Japanese number "4" pronounced the same way as "death", so they try to avoid it. Is it the case for this PR? :trollface: 

Anyway, I assume you plan to add comments for namespaces in the next one, correct?
</blockquote></details>

Right, it may go in another PR. Namespaces are pretty tricky. Somehow, we loose comments for them. Depends on the case they appear and disappear.
___
*[fixtures/preproc_comments.cpp, line 17 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXgy8W0m6ixJ-Hj-zs:-LnmCgKOElxonE7TUK46:b-896fix) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/fixtures/preproc_comments.cpp#L17)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

We can also tests trailing comments:

```
#line xxx
// trailing comment
(EOF)
```
</blockquote></details>

Done.
___
*[native/src/test/resources/parserequest.go, line 1 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXefRSETrLM04b_IeZ:-LnmChmaA8ZUsk7i25Bq:b8dahmw) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/native/src/test/resources/parserequest.go#L1)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Hehe, nice :) Should be a part of `bblfsh-sdk` tool really ;)
</blockquote></details>

We can think about it, where. So far, I left it here.

**Comment by ncordon** [comment]
___
*[native/src/test/resources/parserequest.go, line 1 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXefRSETrLM04b_IeZ:-LoKbChmAnWiyA0lZ1-G:brp7avr) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/native/src/test/resources/parserequest.go#L1)):*
<details><summary><i>Previously, kuba-- (Kuba Podgórski) wrote…</i></summary><blockquote>

We can think about it, where. So far, I left it here.
</blockquote></details>

If this is not used in any other driver to test it, I am good with it being here

**Comment by ncordon** [comment]
___
*[driver/normalizer/normalizer.go, line 136 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXf0HtB85-oxpoB5ig:-LoKcrAN0F4J022tGTyx:b-5i832u) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/driver/normalizer/normalizer.go#L136)):*
<details><summary><i>Previously, kuba-- (Kuba Podgórski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it a good idea to keep comments in the code that refer to a previous state of it? I mean, to have some context about what does this comment mean, one has to go to an older version of the repo and look for `CaseObj("isSystemCase"`

**Review by ncordon — APPROVED** [review]
> Reviewed 18 of 19 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: all files reviewed, 6 unresolved discussions (waiting on @bzz, @creachadair, and @dennwc)

**Comment by ncordon** [comment]
___
*[native/src/test/resources/parserequest.go, line 1 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXefRSETrLM04b_IeZ:-LoLduEq5ERA3DQRVuPh:b-dzr735) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/native/src/test/resources/parserequest.go#L1)):*
<details><summary><i>Previously, ncordon (Nacho Cordón) wrote…</i></summary><blockquote>

If this is not used in any other driver to test it, I am good with it being here
</blockquote></details>

I think we are using 8 spaces instead of 4 elsewhere in Go. Could you change indentation to comply with that, please?

**Review by ncordon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: all files reviewed, 6 unresolved discussions (waiting on @bzz, @creachadair, and @dennwc)

**Review by creachadair — COMMENTED** [review]
> Reviewed 12 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: all files reviewed, 6 unresolved discussions (waiting on @bzz, @dennwc, and @ncordon)

___
*[native/src/test/resources/parserequest.go, line 1 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXefRSETrLM04b_IeZ:-LoLgqbJ7Qll5wdA-gEQ:b-z1pdad) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/native/src/test/resources/parserequest.go#L1)):*
<details><summary><i>Previously, ncordon (Nacho Cordón) wrote…</i></summary><blockquote>

I think we are using 8 spaces instead of 4 elsewhere in Go. Could you change indentation to comply with that, please?
</blockquote></details>

Whatever `gofmt` does should be fine.

**Comment by ncordon** [comment]
___
*[native/src/test/resources/parserequest.go, line 1 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXefRSETrLM04b_IeZ:-LoLkPdzAxy2L0M15EcD:blrpvrq) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/native/src/test/resources/parserequest.go#L1)):*
<details><summary><i>Previously, creachadair (M. J. Fromberger) wrote…</i></summary><blockquote>

Whatever `gofmt` does should be fine.
</blockquote></details>

True. I think in fact it uses tabs (width = 8) instead of spaces :smiley_cat:

**Review by creachadair — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: all files reviewed, 6 unresolved discussions (waiting on @bzz, @dennwc, and @ncordon)

___
*[native/src/test/resources/parserequest.go, line 1 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXefRSETrLM04b_IeZ:-LoLpqnW4IsHWZ1cVf6G:b-z8jfl7) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/native/src/test/resources/parserequest.go#L1)):*
<details><summary><i>Previously, ncordon (Nacho Cordón) wrote…</i></summary><blockquote>

True. I think in fact it uses tabs (width = 8) instead of spaces :smiley_cat: 
</blockquote></details>

It does: Specifically, it uses the [elastic tab stops](http://nickgravgaard.com/elastic-tabstops/) algorithm (as implemented by the [`text/tabwriter`](https://godoc.org/text/tabwriter) package), where tabs indicate alignments and spaces are used as padding.

**Review by kuba-- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: all files reviewed, 6 unresolved discussions (waiting on @bzz, @dennwc, and @ncordon)

___
*[driver/normalizer/normalizer.go, line 136 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXf0HtB85-oxpoB5ig:-LoND2BD1cu4VdCcsg44:btz9hz7) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/driver/normalizer/normalizer.go#L136)):*
<details><summary><i>Previously, ncordon (Nacho Cordón) wrote…</i></summary><blockquote>

Is it a good idea to keep comments in the code that refer to a previous state of it? I mean, to have some context about what does this comment mean, one has to go to an older version of the repo and look for `CaseObj("isSystemCase"`
</blockquote></details>

It's more about - maybe we can think about fix/extend `CasesObj`, so here is a case.
___
*[native/src/test/resources/parserequest.go, line 1 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXefRSETrLM04b_IeZ:-LoNDOi-8JhxK4hhnRLB:bxxuolw) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/native/src/test/resources/parserequest.go#L1)):*
<details><summary><i>Previously, creachadair (M. J. Fromberger) wrote…</i></summary><blockquote>

It does: Specifically, it uses the [elastic tab stops](http://nickgravgaard.com/elastic-tabstops/) algorithm (as implemented by the [`text/tabwriter`](https://godoc.org/text/tabwriter) package), where tabs indicate alignments and spaces are used as padding.
</blockquote></details>

for go it's no brainer - almost everyone uses gofmt on save

**Review by dennwc — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: all files reviewed, 4 unresolved discussions (waiting on @bzz, @dennwc, @kuba--, and @ncordon)

___
*[driver/normalizer/normalizer.go, line 158 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXkNTx1akVFD2ngo8q:-LoQm4UyBr65Vh3w-RtT:b-3foh0a) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/driver/normalizer/normalizer.go#L158)):*
<details><summary><i>Previously, kuba-- (Kuba Podgórski) wrote…</i></summary><blockquote>

How can I use Map(Cases) in this case (where you need to drop _LeadingComments_)?
</blockquote></details>

You can still specify `LeadingComments` in all "from" cases (the first half) and omit them in the "target" (second half).
`Cases` should be able to accept `Fields` instead of `Objs`.

**Review by kuba-- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: all files reviewed, 4 unresolved discussions (waiting on @bzz, @dennwc, and @ncordon)

___
*[driver/normalizer/normalizer.go, line 158 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXkNTx1akVFD2ngo8q:-LoVD0xhBPHc8loeDxzo:bbwg0c6) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/driver/normalizer/normalizer.go#L158)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

You can still specify `LeadingComments` in all "from" cases (the first half) and omit them in the "target" (second half).
`Cases` should be able to accept `Fields` instead of `Objs`.
</blockquote></details>

Looks, we cannot pass Fields to `CaseObj` or to `Case`. `CaseObj` requires implemented `ObjectOp`, so I'm leaving `Fields`. Btw `Fields` in my opinion maybe are less compact (more spaghetti code), but somehow look cleaner (easy to read, easier to understand).

**Review by dennwc — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: all files reviewed, 2 unresolved discussions (waiting on @bzz, @kuba--, and @ncordon)

___
*[driver/normalizer/normalizer.go, line 158 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXkNTx1akVFD2ngo8q:-Lo_-eup1CyaRQBARUcK:b-k1hyzu) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/driver/normalizer/normalizer.go#L158)):*
<details><summary><i>Previously, kuba-- (Kuba Podgórski) wrote…</i></summary><blockquote>

Looks, we cannot pass Fields to `CaseObj` or to `Case`. `CaseObj` requires implemented `ObjectOp`, so I'm leaving `Fields`. Btw `Fields` in my opinion maybe are less compact (more spaghetti code), but somehow look cleaner (easy to read, easier to understand).
</blockquote></details>

Sorry for the confusion, I found a proper way:

```golang
MapSemantic("ASTInclusionStatement", uast.InlineImport{}, MapObj(
		CasesObj("isSystemCase", Obj{},
			Objects{
				Fields{
					// ...
				},
				Fields{
					// ...
				},
			}),
		Obj{
			"Path": UASTType(uast.String{}, Obj{
				"Value":  Var("path"),
				"Format": String(""),
			}),
			"All":   Bool(true),
			"Names": Is(nil),
		},
	)),
```

Notice the `Objects` argument instead of `Objs` - it's a full form that accepts an interface instead of `Obj` maps.
___
*[native/src/test/resources/parserequest.go, line 1 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXefRSETrLM04b_IeZ:-Lo_0O1O5Ffp8MSkllAy:bp658p7) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/native/src/test/resources/parserequest.go#L1)):*
> If this is not used in any other driver to test it

It's not specific to C++. I used the same kind of tool to debug all native drivers. It may be useful for [this section](https://doc.bblf.sh/writing-a-driver/babelfish-sdk.html#building-an-echo-driver) of our docs as well. So I'd rather pull this tool to `bblfsh-sdk`.

**Review by kuba-- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: 13 of 22 files reviewed, 2 unresolved discussions (waiting on @bzz, @creachadair, @dennwc, and @ncordon)

___
*[driver/normalizer/normalizer.go, line 158 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXkNTx1akVFD2ngo8q:-Loycv-F-f0HB18J2x-Y:b-896fix) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/driver/normalizer/normalizer.go#L158)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Sorry for the confusion, I found a proper way:

```golang
MapSemantic("ASTInclusionStatement", uast.InlineImport{}, MapObj(
		CasesObj("isSystemCase", Obj{},
			Objects{
				Fields{
					// ...
				},
				Fields{
					// ...
				},
			}),
		Obj{
			"Path": UASTType(uast.String{}, Obj{
				"Value":  Var("path"),
				"Format": String(""),
			}),
			"All":   Bool(true),
			"Names": Is(nil),
		},
	)),
```

Notice the `Objects` argument instead of `Objs` - it's a full form that accepts an interface instead of `Obj` maps.
</blockquote></details>

Done.
___
*[native/src/test/resources/parserequest.go, line 1 at r1](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-LnXefRSETrLM04b_IeZ:-LoycwUm4yhezDbPeeYe:b-xxf6i0) ([raw file](https://github.com/bblfsh/cpp-driver/blob/09716b56dbbe10bbc9eb2cab303149fa04fc8dc1/native/src/test/resources/parserequest.go#L1)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

> If this is not used in any other driver to test it

It's not specific to C++. I used the same kind of tool to debug all native drivers. It may be useful for [this section](https://doc.bblf.sh/writing-a-driver/babelfish-sdk.html#building-an-echo-driver) of our docs as well. So I'd rather pull this tool to `bblfsh-sdk`.
</blockquote></details>

I'll move it to sdk

**Review by ncordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: 13 of 22 files reviewed, 2 unresolved discussions (waiting on @bzz, @creachadair, @dennwc, and @ncordon)

**Review by dennwc — CHANGES_REQUESTED** [review]
> Reviewed 4 of 19 files at r1, 4 of 5 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: all files reviewed, 1 unresolved discussion (waiting on @bzz and @kuba--)

*[a discussion](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-Loz3ie2AVUCg9QBwJs9:-Loz3ie2AVUCg9QBwJsA:b-qw6sup) (no related file):*
CI fails with the error:
```
panic: optional fields are not allowed in Cases
```
Can you try adding those fields to `Obj{}` (common part for both cases) by changing it to `Fields`?

---

**Review by kuba-- — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63)* status: all files reviewed, 1 unresolved discussion (waiting on @bzz and @dennwc)

*[a discussion](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-Loz3ie2AVUCg9QBwJs9:-LozHFQyByiMWdrgwuNT:b-p35qix) (no related file):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

CI fails with the error:
```
panic: optional fields are not allowed in Cases
```
Can you try adding those fields to `Obj{}` (common part for both cases) by changing it to `Fields`?
</blockquote></details>

But `Obj` is a map (name -> op), so it may work for:
`"Path": String("")`
But for other Fields, which needs to be dropped, not really.
Personally, I've found previous Implementation more readable. CaseObj wrapped by MapObj is not intuitive IMHO.

---

**Review by dennwc — APPROVED** [review]
:lgtm:

> Reviewed 2 of 24 files at r4, 1 of 22 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-:-Lozmf2z5IfnOGdTknLs:bnfp4nl)* status: 3 of 24 files reviewed, all discussions resolved (waiting on @bzz, @creachadair, @dennwc, and @ncordon)

*[a discussion](https://reviewable.io/reviews/bblfsh/cpp-driver/63#-Loz3ie2AVUCg9QBwJs9:-LozmPNn2gvwPvBDP63a:bc9e06z) (no related file):*
<details><summary><i>Previously, kuba-- (Kuba Podgórski) wrote…</i></summary><blockquote>

But `Obj` is a map (name -> op), so it may work for:
`"Path": String("")`
But for other Fields, which needs to be dropped, not really.
Personally, I've found previous Implementation more readable. CaseObj wrapped by MapObj is not intuitive IMHO.
</blockquote></details>

Agree. Sorry that I forgot about the `Optional` limitation in `Cases`.

---

**Pull request merged**
