### PR TITLE
Fix argument transformations for vararg functions

### LINKED ISSUE #51: Variable atype is not defined
From [bblfsh logs](https://github.com/bblfsh/bblfshd/issues/298) we got the following message:

```
rpc error: code = FailedPrecondition desc = construct: key \"Nodes\": elem 1 (*transformer.opObjJoin): key \"Node\": key \"Type\": key \"Arguments\": elem 0 (<nil>): key \"Type\": variable \"atype\" is not defined
```

Files that triggered this error:

```
js/src/jskwgen.cpp
gnu/usr.bin/perl/wince/perlhost.h
gnu/usr.bin/perl/win32/perlhost.h
win32/perlhost.h
external/mit/MesaLib/dist/src/glsl/standalone_scaffolding.cpp
third_party/cpp/civetweb/mod_lua.inl
external/mit/MesaLib/dist/src/mesa/main/tests/stubs.cpp
external/mit/MesaLib/dist/src/mesa/state_tracker/st_glsl_to_tgsi.cpp
```

### PR DESCRIPTION
**Pull request by dennwc**
Fix in fe3728b6b265e25f08bff6fac07c560cab02c8c3 introduced a few more transformation cases for function arguments. But by mistake, it added those cases only to one branch: function with no varargs. Two of three cases used the same state map, so those cases were working for vararg functions as well. However, the last (third) case was missing, leading to errors found by #51.

This PR defines an arguments transform separately and uses it in both branches to make sure this won't happen in the future.

Fixes #51

Signed-off-by: Denys Smirnov <denis.smirnov.91@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/68)

### CODE REVIEW

**Review by kuba-- — APPROVED** [review]

**Comment by ncordon** [comment]
:lgtm: and I have just tested that it works. My only advice would be to include a minimal example that failed before and does not anymore, like:

```cpp
struct x {
    int a;
};

void varargMethod(struct x *y, ...){}
```

**Review by ncordon — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/68)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dennwc)

**Comment by ncordon** [comment]
> My only advice would be to include a minimal example that failed before and does not anymore, like:

In the fixtures I mean

**Review by dennwc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/68)* status: all files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/bblfsh/cpp-driver/68#-LqKn3022LA027sLXCPe:-LqKn3022LA027sLXCPf:bhfhxri) (no related file):*
Blocking until a fixture is added, as @ncordon suggested.

---

**Pull request merged**
