### PR TITLE
Add Operator Role

### PR DESCRIPTION
**Pull request by BFergerson**
same as #59 with DCO fix

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/cpp-driver/62)

### CODE REVIEW

**Comment by bzz** [comment]
CI seems to be failing integration tests
```
+ docker exec ci-build:latest bblfshctl driver install cpp docker-daemon:ci-build:latest
v1 test "/home/travis/gopath/src/github.com/bblfsh/cpp-driver/fixtures/_integration.cpp" failed
exit status 1
The command "go run test.go --bblfshd $BBLFSHD_VERSION ci-build" exited with 1.
```

**Comment by chess-equality** [comment]
Hi all (@bzz , @kuba-- ), I'm working with @BFergerson on this one.

I'm getting `no such image` when running `go run ./test.go` above, would you have any suggestions where I could start looking to solve this?

Thanks.

**Comment by kuba--** [comment]
@chess-equality, could you try to do it in multiple steps:
```
# compile builder
go build -o cpp-build build.go 
# build image cpp-driver
./cpp-build cpp-driver

# compile tester
go build -o cpp-test test.go
# test against cpp-driver image
./cpp-test cpp-driver
```

**Comment by chess-equality** [comment]
@kuba-- Still returning `no such image`.

image

I also noticed it is creating extra images with no tags.

image

I am using Go 1.13.

**Comment by kuba--** [comment]
@chess-equality - looks it can't find the latest image of `bblfshd`.
I suggest to pull it first:
```
docker pull bblfsh/bblfshd:latest
```
and then run:
```
./cpp-test cpp-driver
```

**Comment by chess-equality** [comment]
@kuba-- Thanks, it is working now.

**Comment by BFergerson** [comment]
@kuba--, tests are passing now. Please take another look at this when you get a chance.

Out of curiosity, if/once accepted, do you know when a release will be published? I've also contributed code for bblfsh/php-driver and bblfsh/ruby-driver but those haven't published any new releases since I've contributed. I'm curious when this fix will be included in a release and if there is anything I can do to expedite releases on the other drivers. Thanks.

**Review by kuba-- — APPROVED** [review]

**Comment by kuba--** [comment]
@BFergerson - right now we have `MAINTAINERS` file for each repo. So, you should ping repo's maintainers (I don't think, there is any issue to release a new driver, if it's backward compatible). 
For C++, I'll ask @ncordon and @dennwc (just in case), because IMO would be good to also merge and release https://github.com/bblfsh/cpp-driver/pull/61

**Review by ncordon — APPROVED** [review]
LGTM!

**Review by dennwc — APPROVED** [review]

**Pull request merged**
